version: 2
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/frontend_vue"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "openjdk"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"