name: Backend and frontend CI
on: push

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: adjust maven wrapper permissions
        run: chmod +x mvnw
      - name: test with maven
        run: ./mvnw clean test
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: setup frontend project
        working-directory: ./frontend
        run: npm ci
      - name: run lint
        working-directory: ./frontend
        run: npm run lint
      - name: run unit tests
        working-directory: ./frontend
        run: npm run test:unit
      - name: build backend and include frontend
        run: ./mvnw --batch-mode package -DskipTests
      - name: start liquibase and postgres database
        run: |
          docker-compose down
          docker-compose up -d --build
      - name: start backend in test mode
        working-directory: ./backend/target
        run: java -jar -Dspring.profiles.active=test backend_spring-1.0-SNAPSHOT.jar &
      - name: run cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: ./frontend
          start: npm run dev -- --port 4173 --mode test
          wait-on: 'http://127.0.0.1:4173/'
          browser: chrome

  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: adjust maven wrapper permissions
        run: chmod +x mvnw
      - name: dependency check project
        run: ./mvnw org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=8